#!/usr/bin/env python3
"""Pick reachable first-build mirrors without pinning a single URL.

Writes src/android/mirrors.local.properties (gitignored) used by
settings.gradle.kts. Override with MINIS_BUILD_MIRRORS=cn|auto|off
or MINIS_MAVEN_URLS / MINIS_GRADLE_DIST_URLS (comma-separated).
"""
from __future__ import annotations

import os
import ssl
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ANDROID = ROOT / "src" / "android"
OUT = ANDROID / "mirrors.local.properties"
WRAPPER = ANDROID / "gradle" / "wrapper" / "gradle-wrapper.properties"

GRADLE_VER = "8.11.1"

MAVEN_CANDIDATES = [
    "https://maven.aliyun.com/repository/google",
    "https://maven.aliyun.com/repository/public",
    "https://maven.aliyun.com/repository/gradle-plugin",
    "https://repo.huaweicloud.com/repository/maven",
    "https://mirrors.cloud.tencent.com/nexus/repository/maven-public",
    "https://mirrors.tuna.tsinghua.edu.cn/android/maven2",
    "https://mirrors.ustc.edu.cn/maven/",
]

GRADLE_DIST_CANDIDATES = [
    f"https://mirrors.cloud.tencent.com/gradle/gradle-{GRADLE_VER}-bin.zip",
    f"https://repo.huaweicloud.com/gradle/gradle-{GRADLE_VER}-bin.zip",
    f"https://mirrors.cloud.tencent.com/gradle/gradle-{GRADLE_VER}-all.zip",
    f"https://services.gradle.org/distributions/gradle-{GRADLE_VER}-bin.zip",
]

OFFICIAL_PROBE = [
    "https://dl.google.com/android/maven2/master-index.xml",
    "https://services.gradle.org/distributions/gradle-8.11.1-bin.zip",
]


def env_list(name: str) -> list[str]:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return []
    return [p.strip() for p in raw.replace(";", ",").split(",") if p.strip()]


def reachable(url: str, timeout: float = 3.0) -> bool:
    ctx = ssl.create_default_context()
    req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "OpenMinis-mirror-probe"})
    try:
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
            return 200 <= getattr(resp, "status", 200) < 500
    except Exception:
        try:
            req = urllib.request.Request(url, method="GET", headers={"User-Agent": "OpenMinis-mirror-probe"})
            with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
                return 200 <= getattr(resp, "status", 200) < 500
        except Exception:
            return False


def pick(candidates: list[str], limit: int = 4) -> list[str]:
    chosen = []
    for url in candidates:
        if reachable(url):
            chosen.append(url)
            if len(chosen) >= limit:
                break
    return chosen


def official_ok() -> bool:
    return any(reachable(u, timeout=2.0) for u in OFFICIAL_PROBE)


def main() -> int:
    fetch_gradle = "--fetch-gradle" in sys.argv
    mode = os.environ.get("MINIS_BUILD_MIRRORS", "auto").strip().lower()
    maven_override = env_list("MINIS_MAVEN_URLS")
    dist_override = env_list("MINIS_GRADLE_DIST_URLS")

    use_cn = mode == "cn" or (mode == "auto" and not official_ok())
    if mode == "off":
        use_cn = False

    maven = maven_override or (pick(MAVEN_CANDIDATES) if use_cn else [])
    dist = dist_override or (pick(GRADLE_DIST_CANDIDATES, limit=2) if use_cn else [])

    lines = [
        "# Generated by scripts/pick_build_mirrors.py — do not commit.",
        f"mode={mode}",
        f"useCn={'true' if use_cn else 'false'}",
        "maven.urls=" + ",".join(maven),
        "gradle.dist.urls=" + ",".join(dist),
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    for u in maven:
        print("  maven", u)
    for u in dist:
        print("  gradle-dist", u)
    if not maven and use_cn:
        print("no maven mirror reachable; settings.gradle.kts will still try the CN candidate list", file=sys.stderr)
    if fetch_gradle or dist:
        print("Gradle 8.11.1 distribution candidates (do not commit a single pin):")
        for u in dist or pick(GRADLE_DIST_CANDIDATES, limit=4):
            print("  ", u)
        print("If services.gradle.org is blocked, set gradle-wrapper.properties")
        print("distributionUrl to one of the above locally.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
